name: CI/CD to ECS Fargate

on:
  workflow_run:
    workflows: ["Run Unit Tests"]   # ✅ Runs only after tests finish
    types:
      - completed

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: documentportalliveclass
  ECS_SERVICE: document-portal-service
  ECS_CLUSTER: document-portal-cluster
  ECS_TASK_DEFINITION: .github/workflows/task_definition.json
  CONTAINER_NAME: document-portal-container

permissions:
  id-token: write   # ✅ Required for AWS OIDC authentication
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   # ✅ Deploy only if tests passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_GITHUB_ROLE>
          aws-region:
